# Generated by Django 4.0.5 on 2022-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='log',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
