# Generated by Django 4.0.5 on 2022-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.JSONField(default=1, verbose_name={'message_id': 0}),
            preserve_default=False,
        ),
    ]
