# Generated by Django 4.0.5 on 2022-12-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.JSONField(null=True),
        ),
    ]
