# Generated by Django 4.0.5 on 2022-12-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_user_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
